### ISSUE TITLE
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by xerroxcopy** [xerroxcopy/xerroxgit#18]
```
mm@Vallum xerroxgit % npm run build

> xerroxcopy.github.io@1.0.0 build /Users/mm/Documents/xerroxgit
> webpack --mode development

{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug'
}
{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug'
}
{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug',
  'index.js': '/Users/mm/Documents/xerroxgit/src/index.js',
  'js/db.js': '/Users/mm/Documents/xerroxgit/src/js/db.js',
  'js/google_analytics.js': '/Users/mm/Documents/xerroxgit/src/js/google_analytics.js',
  'js/toggle.js': '/Users/mm/Documents/xerroxgit/src/js/toggle.js',
  'js/tooltip.js': '/Users/mm/Documents/xerroxgit/src/js/tooltip.js'
}
/Users/mm/Documents/xerroxgit/node_modules/webpack-cli/bin/cli.js:281
                                throw err;
                                ^

ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[3].use has an unknown property 'query'. These properties are valid:
   object { ident?, loader?, options? }
    at validate (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/schema-utils/dist/validate.js:105:11)
    at validateSchema (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/validateSchema.js:78:2)
    at create (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/webpack.js:109:24)
    at webpack (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/webpack.js:151:32)
    at f (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/index.js:55:16)
    at processOptions (/Users/mm/Documents/xerroxgit/node_modules/webpack-cli/bin/cli.js:272:16)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/Users/mm/Documents/xerroxgit/node_modules/yargs/yargs.js:576:18)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/mm/Documents/xerroxgit/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at runCli (/Users/mm/Documents/xerroxgit/node_modules/webpack/bin/webpack.js:69:2)
    at Object.<anonymous> (/Users/mm/Documents/xerroxgit/node_modules/webpack/bin/webpack.js:162:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  name: 'ValidationError',
  errors: [
    {
      keyword: 'oneOf',
      dataPath: '.module.rules',
      schemaPath: '#/properties/rules/oneOf',
      params: [Object],
      message: 'should match exactly one schema in oneOf',
      schema: [Array],
      parentSchema: [Object],
      data: [Array],
      children: [Array]
    }
  ],
  schema: {
    definitions: {
      Amd: [Object],
      AssetFilterItemTypes: [Object],
      AssetFilterTypes: [Object],
      AssetGeneratorDataUrl: [Object],
      AssetGeneratorDataUrlFunction: [Object],
      AssetGeneratorDataUrlOptions: [Object],
      AssetGeneratorOptions: [Object],
      AssetInlineGeneratorOptions: [Object],
      AssetModuleFilename: [Object],
      AssetParserDataUrlFunction: [Object],
      AssetParserDataUrlOptions: [Object],
      AssetParserOptions: [Object],
      AssetResourceGeneratorOptions: [Object],
      AuxiliaryComment: [Object],
      Bail: [Object],
      CacheOptions: [Object],
      CacheOptionsNormalized: [Object],
      Charset: [Object],
      ChunkFilename: [Object],
      ChunkFormat: [Object],
      ChunkLoadTimeout: [Object],
      ChunkLoading: [Object],
      ChunkLoadingGlobal: [Object],
      ChunkLoadingType: [Object],
      Clean: [Object],
      CleanOptions: [Object],
      CompareBeforeEmit: [Object],
      Context: [Object],
      CrossOriginLoading: [Object],
      Dependencies: [Object],
      DevServer: [Object],
      DevTool: [Object],
      DevtoolFallbackModuleFilenameTemplate: [Object],
      DevtoolModuleFilenameTemplate: [Object],
      DevtoolNamespace: [Object],
      EmptyGeneratorOptions: [Object],
      EmptyParserOptions: [Object],
      EnabledChunkLoadingTypes: [Object],
      EnabledLibraryTypes: [Object],
      EnabledWasmLoadingTypes: [Object],
      Entry: [Object],
      EntryDescription: [Object],
      EntryDescriptionNormalized: [Object],
      EntryDynamic: [Object],
      EntryDynamicNormalized: [Object],
      EntryFilename: [Object],
      EntryItem: [Object],
      EntryNormalized: [Object],
      EntryObject: [Object],
      EntryRuntime: [Object],
      EntryStatic: [Object],
      EntryStaticNormalized: [Object],
      EntryUnnamed: [Object],
      Environment: [Object],
      Experiments: [Object],
      ExternalItem: [Object],
      ExternalItemFunctionData: [Object],
      ExternalItemValue: [Object],
      Externals: [Object],
      ExternalsPresets: [Object],
      ExternalsType: [Object],
      FileCacheOptions: [Object],
      Filename: [Object],
      FilenameTemplate: [Object],
      FilterItemTypes: [Object],
      FilterTypes: [Object],
      GeneratorOptionsByModuleType: [Object],
      GlobalObject: [Object],
      HashDigest: [Object],
      HashDigestLength: [Object],
      HashFunction: [Object],
      HashSalt: [Object],
      HotUpdateChunkFilename: [Object],
      HotUpdateGlobal: [Object],
      HotUpdateMainFilename: [Object],
      HttpUriOptions: [Object],
      IgnoreWarnings: [Object],
      IgnoreWarningsNormalized: [Object],
      Iife: [Object],
      ImportFunctionName: [Object],
      ImportMetaName: [Object],
      InfrastructureLogging: [Object],
      JavascriptParserOptions: [Object],
      Layer: [Object],
      Library: [Object],
      LibraryCustomUmdCommentObject: [Object],
      LibraryCustomUmdObject: [Object],
      LibraryExport: [Object],
      LibraryName: [Object],
      LibraryOptions: [Object],
      LibraryType: [Object],
      Loader: [Object],
      MemoryCacheOptions: [Object],
      Mode: [Object],
      ModuleFilterItemTypes: [Object],
      ModuleFilterTypes: [Object],
      ModuleOptions: [Object],
      ModuleOptionsNormalized: [Object],
      Name: [Object],
      NoParse: [Object],
      Node: [Object],
      NodeOptions: [Object],
      Optimization: [Object],
      OptimizationRuntimeChunk: [Object],
      OptimizationRuntimeChunkNormalized: [Object],
      OptimizationSplitChunksCacheGroup: [Object],
      OptimizationSplitChunksGetCacheGroups: [Object],
      OptimizationSplitChunksOptions: [Object],
      OptimizationSplitChunksSizes: [Object],
      Output: [Object],
      OutputModule: [Object],
      OutputNormalized: [Object],
      Parallelism: [Object],
      ParserOptionsByModuleType: [Object],
      Path: [Object],
      Pathinfo: [Object],
      Performance: [Object],
      PerformanceOptions: [Object],
      Plugins: [Object],
      Profile: [Object],
      PublicPath: [Object],
      RawPublicPath: [Object],
      RecordsInputPath: [Object],
      RecordsOutputPath: [Object],
      RecordsPath: [Object],
      Resolve: [Object],
      ResolveAlias: [Object],
      ResolveLoader: [Object],
      ResolveOptions: [Object],
      ResolvePluginInstance: [Object],
      RuleSetCondition: [Object],
      RuleSetConditionAbsolute: [Object],
      RuleSetConditionOrConditions: [Object],
      RuleSetConditionOrConditionsAbsolute: [Object],
      RuleSetConditions: [Object],
      RuleSetConditionsAbsolute: [Object],
      RuleSetLoader: [Object],
      RuleSetLoaderOptions: [Object],
      RuleSetLogicalConditions: [Object],
      RuleSetLogicalConditionsAbsolute: [Object],
      RuleSetRule: [Object],
      RuleSetRules: [Object],
      RuleSetUse: [Object],
      RuleSetUseItem: [Object],
      ScriptType: [Object],
      SnapshotOptions: [Object],
      SourceMapFilename: [Object],
      SourcePrefix: [Object],
      StatsOptions: [Object],
      StatsValue: [Object],
      StrictModuleErrorHandling: [Object],
      StrictModuleExceptionHandling: [Object],
      Target: [Object],
      TrustedTypes: [Object],
      UmdNamedDefine: [Object],
      UniqueName: [Object],
      WarningFilterItemTypes: [Object],
      WarningFilterTypes: [Object],
      WasmLoading: [Object],
      WasmLoadingType: [Object],
      Watch: [Object],
      WatchOptions: [Object],
      WebassemblyModuleFilename: [Object],
      WebpackOptionsNormalized: [Object],
      WebpackPluginFunction: [Object],
      WebpackPluginInstance: [Object]
    },
    title: 'WebpackOptions',
    description: 'Options object as provided by the user.',
    type: 'object',
    additionalProperties: false,
    properties: {
      amd: [Object],
      bail: [Object],
      cache: [Object],
      context: [Object],
      dependencies: [Object],
      devServer: [Object],
      devtool: [Object],
      entry: [Object],
      experiments: [Object],
      externals: [Object],
      externalsPresets: [Object],
      externalsType: [Object],
      ignoreWarnings: [Object],
      infrastructureLogging: [Object],
      loader: [Object],
      mode: [Object],
      module: [Object],
      name: [Object],
      node: [Object],
      optimization: [Object],
      output: [Object],
      parallelism: [Object],
      performance: [Object],
      plugins: [Object],
      profile: [Object],
      recordsInputPath: [Object],
      recordsOutputPath: [Object],
      recordsPath: [Object],
      resolve: [Object],
      resolveLoader: [Object],
      snapshot: [Object],
      stats: [Object],
      target: [Object],
      watch: [Object],
      watchOptions: [Object]
    }
  },
  headerName: 'Webpack',
  baseDataPath: 'configuration',
  postFormatter: [Function: postFormatter],
  message: 'Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.\n' +
    " - configuration.module.rules[3].use has an unknown property 'query'. These properties are valid:\n" +
    '   object { ident?, loader?, options? }'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xerroxcopy.github.io@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xerroxcopy.github.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mm/.npm/_logs/2021-09-24T05_34_39_145Z-debug.log
```

**Comment by xerroxcopy** [comment]
there's no `query` key [they say](https://stackoverflow.com/questions/67389400/webpack-unknown-property-query)
error is now 

```
mm@Vallum xerroxgit % npm run build

> xerroxcopy.github.io@1.0.0 build /Users/mm/Documents/xerroxgit
> webpack --mode development

{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug'
}
{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug'
}
{
  'pages/index.html': '/Users/mm/Documents/xerroxgit/src/pages/index.pug',
  'index.js': '/Users/mm/Documents/xerroxgit/src/index.js',
  'js/db.js': '/Users/mm/Documents/xerroxgit/src/js/db.js',
  'js/google_analytics.js': '/Users/mm/Documents/xerroxgit/src/js/google_analytics.js',
  'js/toggle.js': '/Users/mm/Documents/xerroxgit/src/js/toggle.js',
  'js/tooltip.js': '/Users/mm/Documents/xerroxgit/src/js/tooltip.js'
}
(node:4268) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader
(node:4268) [DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:4268) [DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:4268) [DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use JavascriptModulesPlugin.getCompilationHooks().chunkHash instead)
(node:4268) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
/Users/mm/Documents/xerroxgit/node_modules/extract-text-webpack-plugin/dist/index.js:211
          extractedChunk.index = i;
                               ^

TypeError: Cannot set property 'index' of undefined
    at /Users/mm/Documents/xerroxgit/node_modules/extract-text-webpack-plugin/dist/index.js:211:32
    at Set.forEach (<anonymous>)
    at /Users/mm/Documents/xerroxgit/node_modules/extract-text-webpack-plugin/dist/index.js:209:16
    at Hook.eval [as callAsync] (eval at create (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:5:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.seal (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/Compilation.js:2420:27)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/Compiler.js:1109:20
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/Compilation.js:2227:4
    at eval (eval at create (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:376:11
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:355:18
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/neo-async/async.js:2850:39)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:48:16
    at Hook.eval [as callAsync] (eval at create (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/mm/Documents/xerroxgit/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compilation.finish (/Users/mm/Documents/xerroxgit/node_modules/webpack/lib/Compilation.js:2196:28)
    at /Users/mm/Documents/xerroxgit/node_modules/webpack/lib/Compiler.js:1104:19
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xerroxcopy.github.io@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xerroxcopy.github.io@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mm/.npm/_logs/2021-09-24T05_39_35_248Z-debug.log
```

**Comment by xerroxcopy** [comment]
`npm install -D webpack-cli`
`npm link webpack-cli` as per [here](https://stackoverflow.com/questions/49855472/cannot-find-module-webpack-cli)

```
mm@Vallum xerroxgit % webpack --version
webpack 5.53.0
webpack-cli 4.8.0
```

changed webpack.config.js to
```
       {
        test: /\.scss$/,
        use: [{
            loader: MiniCssExtractPlugin.loader
          },
          {
            loader: "css-loader",
            options: {
              sourceMap: true,
              modules: true,
              localIdentName: "[local]___[hash:base64:5]"
            }
          },
          "sass-loader"
        ]
      },
      // {
      //   test: /\.scss$/,
      //   oneOf: [
      //     {
      //       // pugから `require('./hoge.sass?inline')` のように呼ばれた時は、ExtractTextPluginをかけない
      //       resourceQuery: /inline/,
      //       use: sassLoader,
      //     },
      //     {
      //       // それ以外の時は、単純にファイルを生成する
      //       use: [MiniCssExtractPlugin.loader, ...sassLoader],
      //     },
      //   ],
      // },
```

and it now emits files, but error:

```
Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/sass-loader/dist/cjs.js!index.scss:
    Entrypoint mini-css-extract-plugin = *
    [../node_modules/css-loader/dist/cjs.js?!../node_modules/sass-loader/dist/cjs.js!./index.scss] ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/sass-loader/dist/cjs.js!./index.scss 608 bytes {mini-css-extract-plugin} [built] [failed] [1 error]
    
    ERROR in ./index.scss (../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/sass-loader/dist/cjs.js!./index.scss)
    Module build failed (from ../node_modules/css-loader/dist/cjs.js):
    ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
     - options has an unknown property 'localIdentName'. These properties are valid:
       object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals?, esModule? }
        at validate (/Users/mm/Documents/xerroxgit/node_modules/schema-utils/dist/validate.js:96:11)
        at Object.loader (/Users/mm/Documents/xerroxgit/node_modules/css-loader/dist/index.js:36:28)
```

[this](https://stackoverflow.com/questions/57899750/error-while-configuring-css-modules-with-webpack) fixed the issue.

**Comment by xerroxcopy** [comment]
but 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/13182777/134625544-965cced9-66d4-4477-96cc-d9d56b109d99.png">
why??

**Comment by xerroxcopy** [comment]
opening the root index.html showed the correcrt result.
